main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

default/objects/User__c/fields/User_Role__c.field-meta.xml
<CustomField>
    <fullName>User_Role__c</fullName>
    <label>Role</label>
    <referenceTo>User_Role__c</referenceTo>
    <relationshipLabel>Users</relationshipLabel>
    <relationshipName>Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

default/objects/User__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/User_Role__c/User_Role__c.object-meta.xml
<CustomObject>
    <label>User Role</label>
    <nameField>
        <label>User Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/classes/ManageUsersController.cls
public with sharing class ManageUsersController implements Callable
{
    public Object call(String action, Map<String, Object> args)
    {
        Utils.ActionType actionType = Utils.getActionType(action);
        
        switch on actionType
        {
            when GET_USERS_LIST
            {
                return this.getUsers();
            }
            when DELETE_USER
            {
                this.deleteUser((String)args.get('userId'));
                return null;
            }
            when else {
                return null;
            }
        }
    }
    
    private List<User__c> getUsers()
    {
        List<User__c> users = [
            SELECT Id, Name, Username__c, Email__c, User_Role__r.Name, User_Role__c
            FROM User__c
            WHERE User_Role__c != null
            ORDER BY Name
            LIMIT 1000
        ];
        
        System.debug(users);
        
        return users;
    }
    
    private void deleteUser(Id userId)
    {
        User__c user = new User__c(Id = userId);
        
        delete user;
    }
}