main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <label>User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/User__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

default/objects/User__c/fields/User_Role__c.field-meta.xml
<CustomField>
    <fullName>User_Role__c</fullName>
    <label>Role</label>
    <referenceTo>User_Role__c</referenceTo>
    <relationshipLabel>Users</relationshipLabel>
    <relationshipName>Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

default/objects/User__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

default/objects/User_Role__c/User_Role__c.object-meta.xml
<CustomObject>
    <label>User Role</label>
    <nameField>
        <label>User Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/classes/LoginController.cls
public with sharing class LoginController implements Callable {
    public Object call(String action, Map<String, Object> args)
    {
        Utils.ActionType actionType = Utils.getActionType(action);
        String test = '1';
        
        switch on actionType
        {
            when USER_LOGIN
            {
                return this.login((String)args.get('username'), (String)args.get('password'));
            }
            when else {
                return null;
            }
        }
    }

    public String login(String userName, String password)
    {
        List<User__c> users = [
            SELECT Id, User_Role__r.Name, Username__c, Name, Password__c
            FROM User__c
            WHERE Username__c = :userName
        ];
        
        if (users.isEmpty())
        {
            return 'Invalid username';
        }
        else
        {
            User__c user = users[0];
            
            if (user.Password__c == password)
            {
                return user.User_Role__r.Name;
            }
            else
            {
                return 'Invalid password';
            }
        }
    }
}