main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Category__c/fields/Master_Category__c.field-meta.xml
<CustomField>
    <fullName>Master_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Categories</relationshipLabel>
    <relationshipName>Sub_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Product_Configuration__c/Product_Configuration__c.object-meta.xml
<CustomObject>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Product_Configuration__c/fields/Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Api_Name__c</fullName>
    <label>Api Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Product_Configuration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drop Down</fullName>
                <default>true</default>
                <label>Drop Down</label>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/ManageProductController.cls
public with sharing class ManageProductController implements Callable
{
    public Object call(String action, Map<String, Object> args)
    {
        Utils.ActionType actionType = Utils.getActionType(action);
        
        switch on actionType
        {
            when GET_CATEGORIES_LIST
            {
                return this.getCategoriesList();
            }
            when DELETE_CATEGORY
            {
                this.deleteCategory((String)args.get('categoryId'));
                return null;
            }
            when GET_PRODUCT_CONFIGS_LIST
            {
                return this.getConfigList();
            }
            when DELETE_PRODUCT_CONFIG
            {
                this.deleteFieldConfig((String)args.get('configId'));
                return null;
            }
            when else {
                return null;
            }
        }
    }
    
    private List<Category__c> getCategoriesList()
    {
        List<Category__c> categories = [
            SELECT Id, Name, Master_Category__c, Master_Category__r.Name
            FROM Category__c
            ORDER BY Name
        ];

        System.debug(categories);
        
        return categories;
    }
    
    private List<Product_Configuration__c> getConfigList()
    {
        List<Product_Configuration__c> configs = [
            SELECT Id, Name, Type__c, Api_Name__c, Description__c
            FROM Product_Configuration__c
            ORDER BY Name
        ];
        
        System.debug(configs);
        
        return configs;
    }
    
    private void deleteFieldConfig(Id configId)
    {
        Product_Configuration__c config = new Product_Configuration__c(Id = configId);
        
        delete config;
        
        //TODO remove values from all products
    }
    
    private void deleteCategory(Id categoryId)
    {
        Category__c category = new Category__c(Id = categoryId);
        
        delete category;
    }
}