main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Product_Configuration__c/Product_Configuration__c.object-meta.xml
<CustomObject>
    <label>Product Configuration</label>
    <nameField>
        <label>Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Product_Configuration__c/fields/Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Api_Name__c</fullName>
    <label>Api Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Product_Field__c/Product_Field__c.object-meta.xml
<CustomObject>
    <label>Product Field</label>
    <nameField>
        <label>Product Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Product_Field__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Fields</relationshipLabel>
    <relationshipName>Product_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

default/objects/Product_Field__c/fields/Product_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Product_Configuration__c</fullName>
    <label>Product Configuration</label>
    <referenceTo>Product_Configuration__c</referenceTo>
    <relationshipLabel>Product Fields</relationshipLabel>
    <relationshipName>Product_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Product_Field__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/classes/ProductsSearchService.cls
public with sharing class ProductsSearchService
{
    public static  List<List<Product_Field__c>> searchProducts(Set<Id> categoryIds, List<ProductListController.FilterInstanse> filters)
    {
        String query = 'SELECT Value__c, Product__c, Product_Configuration__r.Api_Name__c FROM Product_Field__c WHERE ';
        
        for (ProductListController.FilterInstanse currentFilter : filters)
        {
            String value = currentFilter.value;
            String apiName = currentFilter.key;
            Integer valueIndex = 0;
            
            while (valueIndex < value.length())
            {
                Integer appostropheIndex = value.indexOfChar(Utils.APOSTROPHE_CHAR_NUMBER, valueIndex);
        
                if (appostropheIndex != -1)
                {
                    value = value.substring(0, appostropheIndex) + '\\' + value.substring(appostropheIndex, value.length());
                    valueIndex = appostropheIndex + 2;
                }
                else
                {
                    break;
                }
            }
            
            query += '( Product_Configuration__r.Api_Name__c = ' + '\'' + apiName + '\' AND Value__c = ' + '\'' + value + '\') OR';
        }
        
        query = query.substring(0, query.length()-2);
        query += ' AND Category__c IN :categoryIds ORDER BY Product__c, Product_Configuration__r.Api_Name__c asc';
        
        List<Product_Field__c> productFields = (List<Product_Field__c>)Database.query(query);
        
        Map<Id, List<Product_Field__c>> valuesByProduct = new Map<Id, List<Product_Field__c>>();
        
        for (Product_Field__c currentField : productFields)
        {
            if (!valuesByProduct.containsKey(currentField.Product_Configuration__r.Api_Name__c))
            {
                valuesByProduct.put(currentField.Product_Configuration__r.Api_Name__c, new List<Product_Field__c>());
            }
            
            valuesByProduct.get(currentField.Product_Configuration__r.Api_Name__c).add(currentField);
        }
        
        return valuesByProduct.values();
    }
}