main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

default/objects/Category__c/fields/Master_Category__c.field-meta.xml
<CustomField>
    <fullName>Master_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Categories</relationshipLabel>
    <relationshipName>Sub_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Product_Field__c/Product_Field__c.object-meta.xml
<CustomObject>
    <label>Product Field</label>
    <nameField>
        <label>Product Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/classes/ProductListController.cls
public with sharing class ProductListController implements Callable
{
    public Object call(String action, Map<String, Object> args)
    {
        Utils.ActionType actionType = Utils.getActionType(action);
        
        switch on actionType
        {
            when GET_CHILD_CATEGORIES
            {
                return this.getChildCategories((String)args.get('categoryId'));
            }
            when RECIEVE_PRODUCTS
            {
                return this.retrieveProducts((String)args.get('categoryIds'), (String)args.get('filters'));
            }
            when else
            {
                return null;
            }
        }
    }
    
    private List<Category__c> getChildCategories(Id masterId)
    {
        List<Category__c> categories = [
            SELECT Id, Name
            FROM Category__c
            WHERE Master_Category__c = :masterId
        ];
        
        return categories;
    }
    
    private List<List<Product_Field__c>> retrieveProducts(String filtersSer, String categoryIdsSer)
    {
        List<FilterInstanse> filters = (List<FilterInstanse>)JSON.deserialize(filtersSer, List<FilterInstanse>.class);
        Set<Id> categoryIds = (Set<Id>)JSON.deserialize(categoryIdsSer, Set<Id>.class);
        
        return ProductsSearchService.searchProducts(categoryIds, filters);
    }
    
    public class FilterInstanse
    {
        public String key;
        public String value;
    }
}